const CITIES = [
  // América del Sur
  { name: "Buenos Aires",        country: "ARG", lat: -34.61, lon:  -58.38 },
  { name: "Rosario",             country: "ARG", lat: -32.95, lon:  -60.66 },
  { name: "São Paulo",           country: "BRA", lat: -23.55, lon:  -46.63 },
  { name: "Salvador",            country: "BRA", lat: -12.97, lon:  -38.50 },
  { name: "Curitiba",            country: "BRA", lat: -25.43, lon:  -49.27 },
  { name: "Porto Alegre",        country: "BRA", lat: -30.03, lon:  -51.23 },
  { name: "Porto Velho",         country: "BRA", lat:  -8.76, lon:  -63.90 },
  { name: "Río de Janeiro",      country: "BRA", lat: -22.91, lon:  -43.17 },
  { name: "Brasilia",            country: "BRA", lat: -15.78, lon:  -47.93 },
  { name: "Belo Horizonte",      country: "BRA", lat: -19.92, lon:  -43.94 },
  { name: "Recife",              country: "BRA", lat:  -8.05, lon:  -34.88 },
  { name: "Fortaleza",           country: "BRA", lat:  -3.72, lon:  -38.54 },
  { name: "Manaus",              country: "BRA", lat:  -3.12, lon:  -60.02 },
  { name: "Santiago",            country: "CHI", lat: -33.45, lon:  -70.67 },
  { name: "Lima",                country: "PER", lat: -12.06, lon:  -77.04 },
  { name: "Arequipa",            country: "PER", lat: -16.41, lon:  -71.54 },
  { name: "Bogotá",              country: "COL", lat:   4.71, lon:  -74.07 },
  { name: "Medellín",            country: "COL", lat:   6.25, lon:  -75.56 },
  { name: "Cali",                country: "COL", lat:   3.43, lon:  -76.52 },
  { name: "Barranquilla",        country: "COL", lat:  10.96, lon:  -74.80 },
  { name: "Caracas",             country: "VEN", lat:  10.49, lon:  -66.88 },
  { name: "Maracaibo",           country: "VEN", lat:  10.63, lon:  -71.64 },
  { name: "Quito",               country: "ECU", lat:  -0.22, lon:  -78.51 },
  { name: "Guayaquil",           country: "ECU", lat:  -2.17, lon:  -79.92 },
  { name: "Asunción",            country: "PAR", lat: -25.29, lon:  -57.64 },
  { name: "Montevideo",          country: "URU", lat: -34.90, lon:  -56.19 },
  { name: "La Paz",              country: "BOL", lat: -16.50, lon:  -68.15 },
  { name: "Cochabamba",          country: "BOL", lat: -17.39, lon:  -66.16 },
  { name: "Santa Cruz de la Sierra", country: "BOL", lat: -17.79, lon:  -63.18 },
  { name: "Georgetown",          country: "GUY", lat:   6.80, lon:  -58.16 },
  { name: "Paramaribo",          country: "SUR", lat:   5.87, lon:  -55.17 },
  { name: "Santarém",            country: "BRA", lat:  -2.44, lon:  -54.71 },
  { name: "Iquitos",             country: "PER", lat:  -3.74, lon:  -73.25 },
  { name: "Piura",               country: "PER", lat:  -5.19, lon:  -80.63 },
  { name: "Antofagasta",         country: "CHI", lat: -23.65, lon:  -70.40 },
  { name: "Rancagua",            country: "CHI", lat: -34.17, lon:  -70.74 },
  { name: "Valparaíso",          country: "CHI", lat: -33.05, lon:  -71.62 },
  { name: "Ushuaia",             country: "ARG", lat: -54.80, lon:  -68.30 },
  { name: "Corrientes",          country: "ARG", lat: -27.47, lon:  -58.83 },
  { name: "Belém",               country: "BRA", lat:  -1.46, lon:  -48.50 },

  // América Central y Caribe
  { name: "Ciudad de México",    country: "MEX", lat:  19.43, lon:  -99.13 },
  { name: "Guadalajara",         country: "MEX", lat:  20.67, lon: -103.35 },
  { name: "Monterrey",           country: "MEX", lat:  25.67, lon: -100.31 },
  { name: "Cancún",              country: "MEX", lat:  21.16, lon:  -86.85 },
  { name: "Mérida",              country: "MEX", lat:  20.97, lon:  -89.62 },
  { name: "Tijuana",             country: "MEX", lat:  32.53, lon: -117.04 },
  { name: "Nassau",              country: "BAH", lat:  25.05, lon:  -77.34 },
  { name: "Ciudad de Guatemala", country: "GUA", lat:  14.64, lon:  -90.51 },
  { name: "San Salvador",        country: "ESA", lat:  13.69, lon:  -89.19 },
  { name: "Tegucigalpa",         country: "HON", lat:  14.10, lon:  -87.20 },
  { name: "Managua",             country: "NCA", lat:  12.13, lon:  -86.28 },
  { name: "San José",            country: "CRC", lat:   9.93, lon:  -84.08 },
  { name: "Panamá",              country: "PAN", lat:   8.99, lon:  -79.52 },
  { name: "La Habana",           country: "CUB", lat:  23.13, lon:  -82.38 },
  { name: "Puerto Príncipe",     country: "HAI", lat:  18.54, lon:  -72.34 },
  { name: "Santo Domingo",       country: "DOM", lat:  18.48, lon:  -69.90 },
  { name: "Kingston",            country: "JAM", lat:  17.99, lon:  -76.79 },
  { name: "Bridgetown",          country: "BRB", lat:  13.10, lon:  -59.62 },
  { name: "The Valley",          country: "AIA", lat:  18.22, lon:  -63.05 },
  { name: "Oranjestad",          country: "ARU", lat:  12.52, lon:  -70.03 },

  // América del Norte
  { name: "Washington D.C.",     country: "USA", lat:  38.91, lon:  -77.04 },
  { name: "Nueva York",          country: "USA", lat:  40.71, lon:  -74.01 },
  { name: "Newark",              country: "USA", lat:  40.74, lon:  -74.17 },
  { name: "Philadelphia",        country: "USA", lat:  39.95, lon:  -75.17 },
  { name: "Los Ángeles",         country: "USA", lat:  34.05, lon: -118.24 },
  { name: "Chicago",             country: "USA", lat:  41.85, lon:  -87.65 },
  { name: "Houston",             country: "USA", lat:  29.76, lon:  -95.37 },
  { name: "Miami",               country: "USA", lat:  25.77, lon:  -80.19 },
  { name: "Dallas",              country: "USA", lat:  32.78, lon:  -96.80 },
  { name: "Phoenix",             country: "USA", lat:  33.45, lon: -112.07 },
  { name: "Salt Lake City",      country: "USA", lat:  40.76, lon: -111.89 },
  { name: "San Francisco",       country: "USA", lat:  37.77, lon: -122.42 },
  { name: "Seattle",             country: "USA", lat:  47.61, lon: -122.33 },
  { name: "Boston",              country: "USA", lat:  42.36, lon:  -71.06 },
  { name: "Atlanta",             country: "USA", lat:  33.75, lon:  -84.39 },
  { name: "Denver",              country: "USA", lat:  39.74, lon: -104.98 },
  { name: "Las Vegas",           country: "USA", lat:  36.17, lon: -115.14 },
  { name: "San Diego",           country: "USA", lat:  32.72, lon: -117.16 },
  { name: "Ottawa",              country: "CAN", lat:  45.42, lon:  -75.69 },
  { name: "Toronto",             country: "CAN", lat:  43.70, lon:  -79.42 },
  { name: "Montreal",            country: "CAN", lat:  45.51, lon:  -73.55 },
  { name: "Vancouver",           country: "CAN", lat:  49.25, lon: -123.12 },
  { name: "Calgary",             country: "CAN", lat:  51.04, lon: -114.07 },
  { name: "Nuuk",                country: "GRL", lat:  64.18, lon:  -51.74 },
  { name: "Detroit",             country: "USA", lat:  42.33, lon:  -83.05 },
  { name: "Baltimore",           country: "USA", lat:  39.29, lon:  -76.61 },
  { name: "Nashville",           country: "USA", lat:  36.17, lon:  -86.78 },
  { name: "Bridgeport",          country: "USA", lat:  41.18, lon:  -73.19 },
  { name: "Wichita",             country: "USA", lat:  37.69, lon:  -97.34 },
  { name: "Des Moines",          country: "USA", lat:  41.60, lon:  -93.61 },
  { name: "Quebec",              country: "CAN", lat:  46.81, lon:  -71.21 },
  { name: "Winnipeg",            country: "CAN", lat:  49.90, lon:  -97.14 },
  { name: "Oklahoma City",       country: "USA", lat:  35.47, lon:  -97.52 },
  { name: "Jacksonville",        country: "USA", lat:  30.33, lon:  -81.66 },
  { name: "Orlando",             country: "USA", lat:  28.54, lon:  -81.38 },

  // Europa
  { name: "Londres",             country: "ENG", lat:  51.51, lon:   -0.13 },
  { name: "París",               country: "FRA", lat:  48.85, lon:    2.35 },
  { name: "Toulouse",            country: "FRA", lat:  43.60, lon:    1.44 },
  { name: "Lyon",                country: "FRA", lat:  45.76, lon:    4.84 },
  { name: "Madrid",              country: "ESP", lat:  40.42, lon:   -3.70 },
  { name: "Barcelona",           country: "ESP", lat:  41.39, lon:    2.17 },
  { name: "Valencia",            country: "ESP", lat:  39.47, lon:   -0.38 },
  { name: "Sevilla",             country: "ESP", lat:  37.39, lon:   -5.99 },
  { name: "Lisboa",              country: "POR", lat:  38.72, lon:   -9.14 },
  { name: "Roma",                country: "ITA", lat:  41.90, lon:   12.48 },
  { name: "Milán",               country: "ITA", lat:  45.46, lon:    9.19 },
  { name: "Venecia",             country: "ITA", lat:  45.44, lon:   12.32 },
  { name: "Nápoles",             country: "ITA", lat:  40.85, lon:   14.27 },
  { name: "Berlín",              country: "GER", lat:  52.52, lon:   13.41 },
  { name: "Múnich",              country: "GER", lat:  48.14, lon:   11.58 },
  { name: "Hamburgo",            country: "GER", lat:  53.55, lon:   10.00 },
  { name: "Ámsterdam",           country: "NED", lat:  52.37, lon:    4.90 },
  { name: "Bruselas",            country: "BEL", lat:  50.85, lon:    4.35 },
  { name: "Viena",               country: "AUT", lat:  48.21, lon:   16.37 },
  { name: "Berna",               country: "SUI", lat:  46.95, lon:    7.45 },
  { name: "Zúrich",              country: "SUI", lat:  47.38, lon:    8.54 },
  { name: "Estocolmo",           country: "SWE", lat:  59.33, lon:   18.07 },
  { name: "Oslo",                country: "NOR", lat:  59.91, lon:   10.75 },
  { name: "Copenhague",          country: "DEN", lat:  55.68, lon:   12.57 },
  { name: "Helsinki",            country: "FIN", lat:  60.17, lon:   24.94 },
  { name: "Varsovia",            country: "POL", lat:  52.23, lon:   21.01 },
  { name: "Praga",               country: "CZE", lat:  50.08, lon:   14.44 },
  { name: "Budapest",            country: "HUN", lat:  47.50, lon:   19.04 },
  { name: "Bucarest",            country: "ROU", lat:  44.44, lon:   26.10 },
  { name: "Sofía",               country: "BUL", lat:  42.70, lon:   23.32 },
  { name: "Belgrado",            country: "SRB", lat:  44.82, lon:   20.46 },
  { name: "Atenas",              country: "GRE", lat:  37.98, lon:   23.73 },
  { name: "Kiev",                country: "UKR", lat:  50.45, lon:   30.52 },
  { name: "Moscú",               country: "RUS", lat:  55.75, lon:   37.62 },
  { name: "San Petersburgo",     country: "RUS", lat:  59.95, lon:   30.32 },
  { name: "Estambul",            country: "TUR", lat:  41.01, lon:   28.95 },
  { name: "Manchester",          country: "ENG", lat:  53.48, lon:   -2.24 },
  { name: "Glasgow",             country: "SCO", lat:  55.86, lon:   -4.25 },
  { name: "Dublín",              country: "IRL", lat:  53.33, lon:   -6.25 },
  { name: "Reikiavik",           country: "ISL", lat:  64.13, lon:  -21.94 },
  { name: "Tallinn",             country: "EST", lat:  59.44, lon:   24.75 },
  { name: "Nicosia",             country: "CYP", lat:  35.17, lon:   33.36 },
  { name: "Greenwich",           country: "ENG", lat:  51.48, lon:    0.00 },
  { name: "Birmingham",          country: "ENG", lat:  52.48, lon:   -1.90 },
  { name: "Tórshavn",            country: "FRO", lat:  62.01, lon:   -6.77 },
  { name: "Sarajevo",            country: "BIH", lat:  43.85, lon:   18.36 },
  { name: "Ljubljana",           country: "SVN", lat:  46.05, lon:   14.51 },
  { name: "Vaduz",               country: "LIE", lat:  47.14, lon:    9.52 },
  { name: "Niza",                country: "FRA", lat:  43.70, lon:    7.26 },
  { name: "Minsk",               country: "BLR", lat:  53.90, lon:   27.57 },
  { name: "Brno",                country: "CZE", lat:  49.20, lon:   16.61 },
  { name: "Andorra la Vella",    country: "AND", lat:  42.51, lon:    1.52 },
  { name: "San Marino",          country: "SMR", lat:  43.94, lon:   12.45 },
  { name: "Cork",                country: "IRL", lat:  51.90, lon:   -8.47 },

  // África
  { name: "El Cairo",            country: "EGY", lat:  30.06, lon:   31.25 },
  { name: "Lagos",               country: "NGA", lat:   6.46, lon:    3.38 },
  { name: "Kinshasa",            country: "COD", lat:  -4.32, lon:   15.32 },
  { name: "Johannesburgo",       country: "RSA", lat: -26.20, lon:   28.04 },
  { name: "Ciudad del Cabo",     country: "RSA", lat: -33.93, lon:   18.42 },
  { name: "Nairobi",             country: "KEN", lat:  -1.29, lon:   36.82 },
  { name: "Addis Abeba",         country: "ETH", lat:   9.03, lon:   38.74 },
  { name: "Dar es Salaam",       country: "TAN", lat:  -6.79, lon:   39.21 },
  { name: "Luanda",              country: "ANG", lat:  -8.84, lon:   13.23 },
  { name: "Dakar",               country: "SEN", lat:  14.72, lon:  -17.47 },
  { name: "Accra",               country: "GHA", lat:   5.56, lon:   -0.20 },
  { name: "Abiyán",              country: "CIV", lat:   5.35, lon:   -4.02 },
  { name: "Kartum",              country: "SDN", lat:  15.55, lon:   32.53 },
  { name: "Argel",               country: "ALG", lat:  36.74, lon:    3.06 },
  { name: "Rabat",               country: "MAR", lat:  34.02, lon:   -6.83 },
  { name: "Casablanca",          country: "MAR", lat:  33.59, lon:   -7.62 },
  { name: "Túnez",               country: "TUN", lat:  36.82, lon:   10.17 },
  { name: "Trípoli",             country: "LBA", lat:  32.90, lon:   13.18 },
  { name: "Kampala",             country: "UGA", lat:   0.32, lon:   32.58 },
  { name: "Maputo",              country: "MOZ", lat: -25.97, lon:   32.59 },
  { name: "Harare",              country: "ZIM", lat: -17.83, lon:   31.05 },
  { name: "Antananarivo",        country: "MAD", lat: -18.91, lon:   47.54 },
  { name: "Lomé",                country: "TOG", lat:   6.13, lon:    1.22 },
  { name: "Mogadiscio",          country: "SOM", lat:   2.05, lon:   45.34 },
  { name: "Monrovia",            country: "LBR", lat:   6.30, lon:  -10.80 },
  { name: "Windhoek",            country: "NAM", lat: -22.56, lon:   17.08 },
  { name: "Mamoudzou",           country: "MAY", lat: -12.78, lon:   45.23 },

  // Medio Oriente
  { name: "Riad",                country: "KSA", lat:  24.69, lon:   46.72 },
  { name: "Dubai",               country: "UAE", lat:  25.20, lon:   55.27 },
  { name: "Bagdad",              country: "IRQ", lat:  33.34, lon:   44.40 },
  { name: "Teherán",             country: "IRN", lat:  35.69, lon:   51.39 },
  { name: "Ankara",              country: "TUR", lat:  39.93, lon:   32.86 },
  { name: "Amán",                country: "JOR", lat:  31.96, lon:   35.95 },
  { name: "Beirut",              country: "LIB", lat:  33.89, lon:   35.50 },
  { name: "Kuwait",              country: "KUW", lat:  29.37, lon:   47.98 },
  { name: "Muscat",              country: "OMA", lat:  23.61, lon:   58.59 },
  { name: "Al-Manama",           country: "BHR", lat:  26.22, lon:   50.59 },
  { name: "Doha",                country: "QAT", lat:  25.29, lon:   51.53 },
  { name: "Tel Aviv",            country: "ISR", lat:  32.08, lon:   34.78 },

  // Asia Central y del Sur
  { name: "Karachi",             country: "PAK", lat:  24.86, lon:   67.01 },
  { name: "Delhi",               country: "IND", lat:  28.61, lon:   77.21 },
  { name: "Mumbai",              country: "IND", lat:  19.08, lon:   72.88 },
  { name: "Bangalore",           country: "IND", lat:  12.97, lon:   77.59 },
  { name: "Colombo",             country: "SRI", lat:   6.93, lon:   79.85 },
  { name: "Katmandú",            country: "NEP", lat:  27.71, lon:   85.31 },
  { name: "Dhaka",               country: "BAN", lat:  23.72, lon:   90.41 },
  { name: "Kabul",               country: "AFG", lat:  34.53, lon:   69.17 },
  { name: "Islamabad",           country: "PAK", lat:  33.72, lon:   73.04 },
  { name: "Tashkent",            country: "UZB", lat:  41.30, lon:   69.27 },
  { name: "Almaty",              country: "KAZ", lat:  43.26, lon:   76.95 },
  { name: "Herat",               country: "AFG", lat:  34.34, lon:   62.20 },
  { name: "Petropavl",           country: "KAZ", lat:  54.87, lon:   69.16 },

  // Asia Oriental y Suroriental
  { name: "Beijing",             country: "CHN", lat:  39.91, lon:  116.39 },
  { name: "Shanghái",            country: "CHN", lat:  31.22, lon:  121.47 },
  { name: "Hong Kong",           country: "HKG", lat:  22.32, lon:  114.17 },
  { name: "Tokio",               country: "JPN", lat:  35.68, lon:  139.69 },
  { name: "Osaka",               country: "JPN", lat:  34.69, lon:  135.50 },
  { name: "Seúl",                country: "KOR", lat:  37.57, lon:  126.98 },
  { name: "Pyongyang",           country: "PRK", lat:  39.03, lon:  125.75 },
  { name: "Taipei",              country: "TPE", lat:  25.04, lon:  121.56 },
  { name: "Bangkok",             country: "THA", lat:  13.75, lon:  100.52 },
  { name: "Hanói",               country: "VIE", lat:  21.03, lon:  105.85 },
  { name: "Yakarta",             country: "INA", lat:  -6.21, lon:  106.85 },
  { name: "Kuala Lumpur",        country: "MAS", lat:   3.14, lon:  101.69 },
  { name: "Singapur",            country: "SIN", lat:   1.35, lon:  103.82 },
  { name: "Manila",              country: "PHI", lat:  14.60, lon:  120.98 },
  { name: "Rangún",              country: "MYA", lat:  16.80, lon:   96.16 },
  { name: "Nom Pen",             country: "CAM", lat:  11.57, lon:  104.92 },
  { name: "Ulán Bator",          country: "MGL", lat:  47.91, lon:  106.90 },
  { name: "Vientiane",           country: "LAO", lat:  17.97, lon:  102.60 },
  { name: "Kota Kinabalu",       country: "MAS", lat:   5.98, lon:  116.07 },
  { name: "Hiroshima",           country: "JPN", lat:  34.39, lon:  132.45 },
  { name: "Nagasaki",            country: "JPN", lat:  32.74, lon:  129.87 },
  { name: "Ürümqi",              country: "CHN", lat:  43.82, lon:   87.60 },

  // Oceanía
  { name: "Sídney",              country: "AUS", lat: -33.87, lon:  151.21 },
  { name: "Melbourne",           country: "AUS", lat: -37.81, lon:  144.96 },
  { name: "Brisbane",            country: "AUS", lat: -27.47, lon:  153.03 },
  { name: "Perth",               country: "AUS", lat: -31.95, lon:  115.86 },
  { name: "Auckland",            country: "NZL", lat: -36.86, lon:  174.77 },
  { name: "Wellington",          country: "NZL", lat: -41.29, lon:  174.78 },
  { name: "Port Moresby",        country: "PNG", lat:  -9.44, lon:  147.18 },
];
