const CITIES = [
  // América del Sur
  { name: "Buenos Aires",        country: "ARG", lat: -34.61, lon:  -58.38, diff: "easy" },
  { name: "Rosario",             country: "ARG", lat: -32.95, lon:  -60.66, diff: "medium" },
  { name: "São Paulo",           country: "BRA", lat: -23.55, lon:  -46.63, diff: "easy" },
  { name: "Salvador",            country: "BRA", lat: -12.97, lon:  -38.50, diff: "medium" },
  { name: "Curitiba",            country: "BRA", lat: -25.43, lon:  -49.27, diff: "medium" },
  { name: "Porto Alegre",        country: "BRA", lat: -30.03, lon:  -51.23, diff: "medium" },
  { name: "Porto Velho",         country: "BRA", lat:  -8.76, lon:  -63.90, diff: "hard" },
  { name: "Río de Janeiro",      country: "BRA", lat: -22.91, lon:  -43.17, diff: "easy" },
  { name: "Brasilia",            country: "BRA", lat: -15.78, lon:  -47.93, diff: "easy" },
  { name: "Belo Horizonte",      country: "BRA", lat: -19.92, lon:  -43.94, diff: "medium" },
  { name: "Recife",              country: "BRA", lat:  -8.05, lon:  -34.88, diff: "medium" },
  { name: "Fortaleza",           country: "BRA", lat:  -3.72, lon:  -38.54, diff: "medium" },
  { name: "Manaus",              country: "BRA", lat:  -3.12, lon:  -60.02, diff: "medium" },
  { name: "Santiago",            country: "CHI", lat: -33.45, lon:  -70.67, diff: "easy" },
  { name: "Lima",                country: "PER", lat: -12.06, lon:  -77.04, diff: "easy" },
  { name: "Arequipa",            country: "PER", lat: -16.41, lon:  -71.54, diff: "hard" },
  { name: "Bogotá",              country: "COL", lat:   4.71, lon:  -74.07, diff: "easy" },
  { name: "Medellín",            country: "COL", lat:   6.25, lon:  -75.56, diff: "medium" },
  { name: "Cali",                country: "COL", lat:   3.43, lon:  -76.52, diff: "medium" },
  { name: "Barranquilla",        country: "COL", lat:  10.96, lon:  -74.80, diff: "medium" },
  { name: "Caracas",             country: "VEN", lat:  10.49, lon:  -66.88, diff: "easy" },
  { name: "Maracaibo",           country: "VEN", lat:  10.63, lon:  -71.64, diff: "medium" },
  { name: "Quito",               country: "ECU", lat:  -0.22, lon:  -78.51, diff: "easy" },
  { name: "Guayaquil",           country: "ECU", lat:  -2.17, lon:  -79.92, diff: "medium" },
  { name: "Asunción",            country: "PAR", lat: -25.29, lon:  -57.64, diff: "medium" },
  { name: "Montevideo",          country: "URU", lat: -34.90, lon:  -56.19, diff: "easy" },
  { name: "La Paz",              country: "BOL", lat: -16.50, lon:  -68.15, diff: "easy" },
  { name: "Cochabamba",          country: "BOL", lat: -17.39, lon:  -66.16, diff: "hard" },
  { name: "Santa Cruz de la Sierra", country: "BOL", lat: -17.79, lon:  -63.18, diff: "medium" },
  { name: "Georgetown",          country: "GUY", lat:   6.80, lon:  -58.16, diff: "hard" },
  { name: "Paramaribo",          country: "SUR", lat:   5.87, lon:  -55.17, diff: "hard" },
  { name: "Santarém",            country: "BRA", lat:  -2.44, lon:  -54.71, diff: "hard" },
  { name: "Iquitos",             country: "PER", lat:  -3.74, lon:  -73.25, diff: "hard" },
  { name: "Piura",               country: "PER", lat:  -5.19, lon:  -80.63, diff: "hard" },
  { name: "Antofagasta",         country: "CHI", lat: -23.65, lon:  -70.40, diff: "hard" },
  { name: "Rancagua",            country: "CHI", lat: -34.17, lon:  -70.74, diff: "hard" },
  { name: "Valparaíso",          country: "CHI", lat: -33.05, lon:  -71.62, diff: "medium" },
  { name: "Ushuaia",             country: "ARG", lat: -54.80, lon:  -68.30, diff: "medium" },
  { name: "Corrientes",          country: "ARG", lat: -27.47, lon:  -58.83, diff: "hard" },
  { name: "Belém",               country: "BRA", lat:  -1.46, lon:  -48.50, diff: "medium" },

  // América Central y Caribe
  { name: "Ciudad de México",    country: "MEX", lat:  19.43, lon:  -99.13, diff: "easy" },
  { name: "Guadalajara",         country: "MEX", lat:  20.67, lon: -103.35, diff: "medium" },
  { name: "Monterrey",           country: "MEX", lat:  25.67, lon: -100.31, diff: "medium" },
  { name: "Cancún",              country: "MEX", lat:  21.16, lon:  -86.85, diff: "medium" },
  { name: "Mérida",              country: "MEX", lat:  20.97, lon:  -89.62, diff: "medium" },
  { name: "Tijuana",             country: "MEX", lat:  32.53, lon: -117.04, diff: "medium" },
  { name: "Nassau",              country: "BAH", lat:  25.05, lon:  -77.34, diff: "medium" },
  { name: "Ciudad de Guatemala", country: "GUA", lat:  14.64, lon:  -90.51, diff: "medium" },
  { name: "San Salvador",        country: "ESA", lat:  13.69, lon:  -89.19, diff: "medium" },
  { name: "Tegucigalpa",         country: "HON", lat:  14.10, lon:  -87.20, diff: "medium" },
  { name: "Managua",             country: "NCA", lat:  12.13, lon:  -86.28, diff: "medium" },
  { name: "San José",            country: "CRC", lat:   9.93, lon:  -84.08, diff: "medium" },
  { name: "Panamá",              country: "PAN", lat:   8.99, lon:  -79.52, diff: "easy" },
  { name: "La Habana",           country: "CUB", lat:  23.13, lon:  -82.38, diff: "easy" },
  { name: "Puerto Príncipe",     country: "HAI", lat:  18.54, lon:  -72.34, diff: "medium" },
  { name: "Santo Domingo",       country: "DOM", lat:  18.48, lon:  -69.90, diff: "medium" },
  { name: "Kingston",            country: "JAM", lat:  17.99, lon:  -76.79, diff: "medium" },
  { name: "Bridgetown",          country: "BRB", lat:  13.10, lon:  -59.62, diff: "hard" },
  { name: "The Valley",          country: "AIA", lat:  18.22, lon:  -63.05, diff: "hard" },
  { name: "Oranjestad",          country: "ARU", lat:  12.52, lon:  -70.03, diff: "hard" },

  // América del Norte
  { name: "Washington D.C.",     country: "USA", lat:  38.91, lon:  -77.04, diff: "easy" },
  { name: "Nueva York",          country: "USA", lat:  40.71, lon:  -74.01, diff: "easy" },
  { name: "Newark",              country: "USA", lat:  40.74, lon:  -74.17, diff: "medium" },
  { name: "Philadelphia",        country: "USA", lat:  39.95, lon:  -75.17, diff: "medium" },
  { name: "Los Ángeles",         country: "USA", lat:  34.05, lon: -118.24, diff: "easy" },
  { name: "Chicago",             country: "USA", lat:  41.85, lon:  -87.65, diff: "easy" },
  { name: "Houston",             country: "USA", lat:  29.76, lon:  -95.37, diff: "easy" },
  { name: "Miami",               country: "USA", lat:  25.77, lon:  -80.19, diff: "easy" },
  { name: "Dallas",              country: "USA", lat:  32.78, lon:  -96.80, diff: "medium" },
  { name: "Phoenix",             country: "USA", lat:  33.45, lon: -112.07, diff: "medium" },
  { name: "Salt Lake City",      country: "USA", lat:  40.76, lon: -111.89, diff: "medium" },
  { name: "San Francisco",       country: "USA", lat:  37.77, lon: -122.42, diff: "easy" },
  { name: "Seattle",             country: "USA", lat:  47.61, lon: -122.33, diff: "easy" },
  { name: "Boston",              country: "USA", lat:  42.36, lon:  -71.06, diff: "easy" },
  { name: "Atlanta",             country: "USA", lat:  33.75, lon:  -84.39, diff: "medium" },
  { name: "Denver",              country: "USA", lat:  39.74, lon: -104.98, diff: "medium" },
  { name: "Las Vegas",           country: "USA", lat:  36.17, lon: -115.14, diff: "easy" },
  { name: "San Diego",           country: "USA", lat:  32.72, lon: -117.16, diff: "medium" },
  { name: "Ottawa",              country: "CAN", lat:  45.42, lon:  -75.69, diff: "medium" },
  { name: "Toronto",             country: "CAN", lat:  43.70, lon:  -79.42, diff: "easy" },
  { name: "Montreal",            country: "CAN", lat:  45.51, lon:  -73.55, diff: "easy" },
  { name: "Vancouver",           country: "CAN", lat:  49.25, lon: -123.12, diff: "easy" },
  { name: "Calgary",             country: "CAN", lat:  51.04, lon: -114.07, diff: "medium" },
  { name: "Nuuk",                country: "GRL", lat:  64.18, lon:  -51.74, diff: "hard" },
  { name: "Detroit",             country: "USA", lat:  42.33, lon:  -83.05, diff: "medium" },
  { name: "Baltimore",           country: "USA", lat:  39.29, lon:  -76.61, diff: "medium" },
  { name: "Nashville",           country: "USA", lat:  36.17, lon:  -86.78, diff: "medium" },
  { name: "Bridgeport",          country: "USA", lat:  41.18, lon:  -73.19, diff: "hard" },
  { name: "Wichita",             country: "USA", lat:  37.69, lon:  -97.34, diff: "hard" },
  { name: "Des Moines",          country: "USA", lat:  41.60, lon:  -93.61, diff: "hard" },
  { name: "Quebec",              country: "CAN", lat:  46.81, lon:  -71.21, diff: "medium" },
  { name: "Winnipeg",            country: "CAN", lat:  49.90, lon:  -97.14, diff: "medium" },
  { name: "Oklahoma City",       country: "USA", lat:  35.47, lon:  -97.52, diff: "medium" },
  { name: "Jacksonville",        country: "USA", lat:  30.33, lon:  -81.66, diff: "medium" },
  { name: "Orlando",             country: "USA", lat:  28.54, lon:  -81.38, diff: "medium" },

  // Europa
  { name: "Londres",             country: "ENG", lat:  51.51, lon:   -0.13, diff: "easy" },
  { name: "París",               country: "FRA", lat:  48.85, lon:    2.35, diff: "easy" },
  { name: "Toulouse",            country: "FRA", lat:  43.60, lon:    1.44, diff: "medium" },
  { name: "Lyon",                country: "FRA", lat:  45.76, lon:    4.84, diff: "medium" },
  { name: "Madrid",              country: "ESP", lat:  40.42, lon:   -3.70, diff: "easy" },
  { name: "Barcelona",           country: "ESP", lat:  41.39, lon:    2.17, diff: "easy" },
  { name: "Valencia",            country: "ESP", lat:  39.47, lon:   -0.38, diff: "medium" },
  { name: "Sevilla",             country: "ESP", lat:  37.39, lon:   -5.99, diff: "medium" },
  { name: "Lisboa",              country: "POR", lat:  38.72, lon:   -9.14, diff: "easy" },
  { name: "Roma",                country: "ITA", lat:  41.90, lon:   12.48, diff: "easy" },
  { name: "Milán",               country: "ITA", lat:  45.46, lon:    9.19, diff: "easy" },
  { name: "Venecia",             country: "ITA", lat:  45.44, lon:   12.32, diff: "easy" },
  { name: "Nápoles",             country: "ITA", lat:  40.85, lon:   14.27, diff: "medium" },
  { name: "Berlín",              country: "GER", lat:  52.52, lon:   13.41, diff: "easy" },
  { name: "Múnich",              country: "GER", lat:  48.14, lon:   11.58, diff: "easy" },
  { name: "Hamburgo",            country: "GER", lat:  53.55, lon:   10.00, diff: "medium" },
  { name: "Ámsterdam",           country: "NED", lat:  52.37, lon:    4.90, diff: "easy" },
  { name: "Bruselas",            country: "BEL", lat:  50.85, lon:    4.35, diff: "easy" },
  { name: "Viena",               country: "AUT", lat:  48.21, lon:   16.37, diff: "easy" },
  { name: "Berna",               country: "SUI", lat:  46.95, lon:    7.45, diff: "medium" },
  { name: "Zúrich",              country: "SUI", lat:  47.38, lon:    8.54, diff: "medium" },
  { name: "Estocolmo",           country: "SWE", lat:  59.33, lon:   18.07, diff: "easy" },
  { name: "Oslo",                country: "NOR", lat:  59.91, lon:   10.75, diff: "easy" },
  { name: "Copenhague",          country: "DEN", lat:  55.68, lon:   12.57, diff: "easy" },
  { name: "Helsinki",            country: "FIN", lat:  60.17, lon:   24.94, diff: "easy" },
  { name: "Varsovia",            country: "POL", lat:  52.23, lon:   21.01, diff: "medium" },
  { name: "Praga",               country: "CZE", lat:  50.08, lon:   14.44, diff: "easy" },
  { name: "Budapest",            country: "HUN", lat:  47.50, lon:   19.04, diff: "easy" },
  { name: "Bucarest",            country: "ROU", lat:  44.44, lon:   26.10, diff: "medium" },
  { name: "Sofía",               country: "BUL", lat:  42.70, lon:   23.32, diff: "medium" },
  { name: "Belgrado",            country: "SRB", lat:  44.82, lon:   20.46, diff: "medium" },
  { name: "Atenas",              country: "GRE", lat:  37.98, lon:   23.73, diff: "easy" },
  { name: "Kiev",                country: "UKR", lat:  50.45, lon:   30.52, diff: "medium" },
  { name: "Moscú",               country: "RUS", lat:  55.75, lon:   37.62, diff: "easy" },
  { name: "San Petersburgo",     country: "RUS", lat:  59.95, lon:   30.32, diff: "medium" },
  { name: "Estambul",            country: "TUR", lat:  41.01, lon:   28.95, diff: "easy" },
  { name: "Manchester",          country: "ENG", lat:  53.48, lon:   -2.24, diff: "medium" },
  { name: "Glasgow",             country: "SCO", lat:  55.86, lon:   -4.25, diff: "medium" },
  { name: "Dublín",              country: "IRL", lat:  53.33, lon:   -6.25, diff: "easy" },
  { name: "Reikiavik",           country: "ISL", lat:  64.13, lon:  -21.94, diff: "medium" },
  { name: "Tallinn",             country: "EST", lat:  59.44, lon:   24.75, diff: "hard" },
  { name: "Nicosia",             country: "CYP", lat:  35.17, lon:   33.36, diff: "hard" },
  { name: "Greenwich",           country: "ENG", lat:  51.48, lon:    0.00, diff: "hard" },
  { name: "Birmingham",          country: "ENG", lat:  52.48, lon:   -1.90, diff: "medium" },
  { name: "Tórshavn",            country: "FRO", lat:  62.01, lon:   -6.77, diff: "hard" },
  { name: "Sarajevo",            country: "BIH", lat:  43.85, lon:   18.36, diff: "medium" },
  { name: "Ljubljana",           country: "SVN", lat:  46.05, lon:   14.51, diff: "medium" },
  { name: "Vaduz",               country: "LIE", lat:  47.14, lon:    9.52, diff: "hard" },
  { name: "Niza",                country: "FRA", lat:  43.70, lon:    7.26, diff: "medium" },
  { name: "Minsk",               country: "BLR", lat:  53.90, lon:   27.57, diff: "medium" },
  { name: "Brno",                country: "CZE", lat:  49.20, lon:   16.61, diff: "hard" },
  { name: "Andorra la Vella",    country: "AND", lat:  42.51, lon:    1.52, diff: "hard" },
  { name: "San Marino",          country: "SMR", lat:  43.94, lon:   12.45, diff: "hard" },
  { name: "Cork",                country: "IRL", lat:  51.90, lon:   -8.47, diff: "hard" },

  // África
  { name: "El Cairo",            country: "EGY", lat:  30.06, lon:   31.25, diff: "easy" },
  { name: "Lagos",               country: "NGA", lat:   6.46, lon:    3.38, diff: "easy" },
  { name: "Kinshasa",            country: "COD", lat:  -4.32, lon:   15.32, diff: "medium" },
  { name: "Johannesburgo",       country: "RSA", lat: -26.20, lon:   28.04, diff: "easy" },
  { name: "Ciudad del Cabo",     country: "RSA", lat: -33.93, lon:   18.42, diff: "easy" },
  { name: "Nairobi",             country: "KEN", lat:  -1.29, lon:   36.82, diff: "medium" },
  { name: "Addis Abeba",         country: "ETH", lat:   9.03, lon:   38.74, diff: "medium" },
  { name: "Dar es Salaam",       country: "TAN", lat:  -6.79, lon:   39.21, diff: "medium" },
  { name: "Luanda",              country: "ANG", lat:  -8.84, lon:   13.23, diff: "medium" },
  { name: "Dakar",               country: "SEN", lat:  14.72, lon:  -17.47, diff: "medium" },
  { name: "Accra",               country: "GHA", lat:   5.56, lon:   -0.20, diff: "medium" },
  { name: "Abiyán",              country: "CIV", lat:   5.35, lon:   -4.02, diff: "hard" },
  { name: "Kartum",              country: "SDN", lat:  15.55, lon:   32.53, diff: "medium" },
  { name: "Argel",               country: "ALG", lat:  36.74, lon:    3.06, diff: "medium" },
  { name: "Rabat",               country: "MAR", lat:  34.02, lon:   -6.83, diff: "medium" },
  { name: "Casablanca",          country: "MAR", lat:  33.59, lon:   -7.62, diff: "easy" },
  { name: "Túnez",               country: "TUN", lat:  36.82, lon:   10.17, diff: "medium" },
  { name: "Trípoli",             country: "LBA", lat:  32.90, lon:   13.18, diff: "medium" },
  { name: "Kampala",             country: "UGA", lat:   0.32, lon:   32.58, diff: "medium" },
  { name: "Maputo",              country: "MOZ", lat: -25.97, lon:   32.59, diff: "medium" },
  { name: "Harare",              country: "ZIM", lat: -17.83, lon:   31.05, diff: "medium" },
  { name: "Antananarivo",        country: "MAD", lat: -18.91, lon:   47.54, diff: "hard" },
  { name: "Lomé",                country: "TOG", lat:   6.13, lon:    1.22, diff: "hard" },
  { name: "Mogadiscio",          country: "SOM", lat:   2.05, lon:   45.34, diff: "medium" },
  { name: "Monrovia",            country: "LBR", lat:   6.30, lon:  -10.80, diff: "hard" },
  { name: "Windhoek",            country: "NAM", lat: -22.56, lon:   17.08, diff: "hard" },
  { name: "Mamoudzou",           country: "MAY", lat: -12.78, lon:   45.23, diff: "hard" },

  // Medio Oriente
  { name: "Riad",                country: "KSA", lat:  24.69, lon:   46.72, diff: "easy" },
  { name: "Dubai",               country: "UAE", lat:  25.20, lon:   55.27, diff: "easy" },
  { name: "Bagdad",              country: "IRQ", lat:  33.34, lon:   44.40, diff: "easy" },
  { name: "Teherán",             country: "IRN", lat:  35.69, lon:   51.39, diff: "easy" },
  { name: "Ankara",              country: "TUR", lat:  39.93, lon:   32.86, diff: "medium" },
  { name: "Amán",                country: "JOR", lat:  31.96, lon:   35.95, diff: "medium" },
  { name: "Beirut",              country: "LIB", lat:  33.89, lon:   35.50, diff: "medium" },
  { name: "Kuwait",              country: "KUW", lat:  29.37, lon:   47.98, diff: "medium" },
  { name: "Muscat",              country: "OMA", lat:  23.61, lon:   58.59, diff: "medium" },
  { name: "Al-Manama",           country: "BHR", lat:  26.22, lon:   50.59, diff: "hard" },
  { name: "Doha",                country: "QAT", lat:  25.29, lon:   51.53, diff: "medium" },
  { name: "Tel Aviv",            country: "ISR", lat:  32.08, lon:   34.78, diff: "easy" },

  // Asia Central y del Sur
  { name: "Karachi",             country: "PAK", lat:  24.86, lon:   67.01, diff: "medium" },
  { name: "Delhi",               country: "IND", lat:  28.61, lon:   77.21, diff: "easy" },
  { name: "Mumbai",              country: "IND", lat:  19.08, lon:   72.88, diff: "easy" },
  { name: "Bangalore",           country: "IND", lat:  12.97, lon:   77.59, diff: "medium" },
  { name: "Colombo",             country: "SRI", lat:   6.93, lon:   79.85, diff: "medium" },
  { name: "Katmandú",            country: "NEP", lat:  27.71, lon:   85.31, diff: "medium" },
  { name: "Dhaka",               country: "BAN", lat:  23.72, lon:   90.41, diff: "medium" },
  { name: "Kabul",               country: "AFG", lat:  34.53, lon:   69.17, diff: "medium" },
  { name: "Islamabad",           country: "PAK", lat:  33.72, lon:   73.04, diff: "medium" },
  { name: "Tashkent",            country: "UZB", lat:  41.30, lon:   69.27, diff: "hard" },
  { name: "Almaty",              country: "KAZ", lat:  43.26, lon:   76.95, diff: "medium" },
  { name: "Herat",               country: "AFG", lat:  34.34, lon:   62.20, diff: "hard" },
  { name: "Petropavl",           country: "KAZ", lat:  54.87, lon:   69.16, diff: "hard" },

  // Asia Oriental y Suroriental
  { name: "Beijing",             country: "CHN", lat:  39.91, lon:  116.39, diff: "easy" },
  { name: "Shanghái",            country: "CHN", lat:  31.22, lon:  121.47, diff: "easy" },
  { name: "Hong Kong",           country: "HKG", lat:  22.32, lon:  114.17, diff: "easy" },
  { name: "Tokio",               country: "JPN", lat:  35.68, lon:  139.69, diff: "easy" },
  { name: "Osaka",               country: "JPN", lat:  34.69, lon:  135.50, diff: "medium" },
  { name: "Seúl",                country: "KOR", lat:  37.57, lon:  126.98, diff: "easy" },
  { name: "Pyongyang",           country: "PRK", lat:  39.03, lon:  125.75, diff: "medium" },
  { name: "Taipei",              country: "TPE", lat:  25.04, lon:  121.56, diff: "medium" },
  { name: "Bangkok",             country: "THA", lat:  13.75, lon:  100.52, diff: "easy" },
  { name: "Hanói",               country: "VIE", lat:  21.03, lon:  105.85, diff: "medium" },
  { name: "Yakarta",             country: "INA", lat:  -6.21, lon:  106.85, diff: "medium" },
  { name: "Kuala Lumpur",        country: "MAS", lat:   3.14, lon:  101.69, diff: "medium" },
  { name: "Singapur",            country: "SIN", lat:   1.35, lon:  103.82, diff: "easy" },
  { name: "Manila",              country: "PHI", lat:  14.60, lon:  120.98, diff: "medium" },
  { name: "Rangún",              country: "MYA", lat:  16.80, lon:   96.16, diff: "hard" },
  { name: "Nom Pen",             country: "CAM", lat:  11.57, lon:  104.92, diff: "hard" },
  { name: "Ulán Bator",          country: "MGL", lat:  47.91, lon:  106.90, diff: "hard" },
  { name: "Vientiane",           country: "LAO", lat:  17.97, lon:  102.60, diff: "hard" },
  { name: "Kota Kinabalu",       country: "MAS", lat:   5.98, lon:  116.07, diff: "hard" },
  { name: "Hiroshima",           country: "JPN", lat:  34.39, lon:  132.45, diff: "medium" },
  { name: "Nagasaki",            country: "JPN", lat:  32.74, lon:  129.87, diff: "medium" },
  { name: "Ürümqi",              country: "CHN", lat:  43.82, lon:   87.60, diff: "hard" },

  // Oceanía
  { name: "Sídney",              country: "AUS", lat: -33.87, lon:  151.21, diff: "easy" },
  { name: "Melbourne",           country: "AUS", lat: -37.81, lon:  144.96, diff: "easy" },
  { name: "Brisbane",            country: "AUS", lat: -27.47, lon:  153.03, diff: "medium" },
  { name: "Perth",               country: "AUS", lat: -31.95, lon:  115.86, diff: "medium" },
  { name: "Auckland",            country: "NZL", lat: -36.86, lon:  174.77, diff: "medium" },
  { name: "Wellington",          country: "NZL", lat: -41.29, lon:  174.78, diff: "medium" },
  { name: "Port Moresby",        country: "PNG", lat:  -9.44, lon:  147.18, diff: "hard" },
];

// Desbloqueo progresivo por respuestas correctas:
//   < 5 correctas  → solo fáciles
//   5–14 correctas → fáciles + medias
//   ≥ 15 correctas → cualquier categoría
const CITY_UNLOCKS = { medium: 5, hard: 15 };

// Cada dificultad tiene su propia cola barajada que se rellena al agotarse,
// así no se repiten ciudades hasta haber pasado por todas las de ese nivel.
function makeCityQueues() {
  const shuffle = arr => {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  };
  return {
    easy:   { list: shuffle(CITIES.filter(c => c.diff === 'easy')),   i: 0 },
    medium: { list: shuffle(CITIES.filter(c => c.diff === 'medium')), i: 0 },
    hard:   { list: shuffle(CITIES.filter(c => c.diff === 'hard')),   i: 0 },
    _shuffle: shuffle,
  };
}

// Elige la siguiente ciudad según cuántas correctas lleva el jugador.
function pickCity(queues, correctCount) {
  const tiers = ['easy'];
  if (correctCount >= CITY_UNLOCKS.medium) tiers.push('medium');
  if (correctCount >= CITY_UNLOCKS.hard)   tiers.push('hard');
  const tier = tiers[Math.floor(Math.random() * tiers.length)];
  const q = queues[tier];
  if (q.i >= q.list.length) { queues._shuffle(q.list); q.i = 0; }
  return q.list[q.i++];
}
