// Países del mundo divididos por reconocimiento de bandera a nivel mundial
// easy   → banderas muy icónicas y ampliamente reconocidas
// medium → banderas conocidas regionalmente o con elementos distintivos
// hard   → banderas poco conocidas, similares entre sí o de países pequeños

const COUNTRIES = {

  easy: [
    "Estados Unidos",
    "Reino Unido",
    "Canadá",
    "Brasil",
    "Japón",
    "China",
    "Australia",
    "Francia",
    "Alemania",
    "Italia",
    "España",
    "México",
    "Argentina",
    "Sudáfrica",
    "India",
    "Rusia",
    "Suiza",
    "Suecia",
    "Noruega",
    "Dinamarca",
    "Grecia",
    "Turquía",
    "Israel",
    "Arabia Saudita",
    "Corea del Sur",
    "Portugal",
    "Países Bajos",
    "Nueva Zelanda",
    "Jamaica",
    "Kenia",
  ],

  medium: [
    "Afganistán",
    "Albania",
    "Argelia",
    "Angola",
    "Austria",
    "Azerbaiyán",
    "Baréin",
    "Bangladés",
    "Bélgica",
    "Bolivia",
    "Bosnia y Herzegovina",
    "Botsuana",
    "Bulgaria",
    "Camboya",
    "Camerún",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Croacia",
    "Cuba",
    "República Checa",
    "Inglaterra",
    "Escocia",
    "Gales",
    "Irlanda del Norte",
    "República Democrática del Congo",
    "Ecuador",
    "Egipto",
    "El Salvador",
    "Etiopía",
    "Finlandia",
    "Ghana",
    "Guatemala",
    "Honduras",
    "Hungría",
    "Islandia",
    "Indonesia",
    "Irán",
    "Irak",
    "Irlanda",
    "Jordania",
    "Kazajistán",
    "Kuwait",
    "Líbano",
    "Libia",
    "Malasia",
    "Marruecos",
    "Mozambique",
    "Myanmar",
    "Nepal",
    "Nicaragua",
    "Nigeria",
    "Corea del Norte",
    "Omán",
    "Pakistán",
    "Panamá",
    "Paraguay",
    "Perú",
    "Filipinas",
    "Polonia",
    "Catar",
    "Rumanía",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Singapur",
    "Eslovaquia",
    "Sri Lanka",
    "Sudán",
    "Siria",
    "Taiwán",
    "Tanzania",
    "Tailandia",
    "Túnez",
    "Uganda",
    "Ucrania",
    "Emiratos Árabes Unidos",
    "Uruguay",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabue",
  ],

  hard: [
    "Andorra",
    "Antigua y Barbuda",
    "Armenia",
    "Bahamas",
    "Barbados",
    "Bielorrusia",
    "Belice",
    "Benín",
    "Bután",
    "Brunéi",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "República Centroafricana",
    "Chipre",
    "Chad",
    "Comoras",
    "Congo",
    "Yibuti",
    "Dominica",
    "República Dominicana",
    "Guinea Ecuatorial",
    "Eritrea",
    "Estonia",
    "Esuatini",
    "Fiyi",
    "Gabón",
    "Gambia",
    "Georgia",
    "Granada",
    "Guinea",
    "Guinea-Bisáu",
    "Guyana",
    "Haití",
    "Kiribati",
    "Kosovo",
    "Kirguistán",
    "Laos",
    "Letonia",
    "Lesoto",
    "Liberia",
    "Liechtenstein",
    "Lituania",
    "Luxemburgo",
    "Madagascar",
    "Malaui",
    "Maldivas",
    "Malí",
    "Malta",
    "Islas Marshall",
    "Mauritania",
    "Mauricio",
    "Micronesia",
    "Moldavia",
    "Mónaco",
    "Mongolia",
    "Montenegro",
    "Namibia",
    "Nauru",
    "Níger",
    "Macedonia del Norte",
    "Palaos",
    "Palestina",
    "Papúa Nueva Guinea",
    "Ruanda",
    "San Cristóbal y Nieves",
    "Santa Lucía",
    "San Vicente y las Granadinas",
    "Samoa",
    "San Marino",
    "Santo Tomé y Príncipe",
    "Sierra Leona",
    "Eslovenia",
    "Islas Salomón",
    "Somalia",
    "Sudán del Sur",
    "Surinam",
    "Tayikistán",
    "Timor Oriental",
    "Togo",
    "Tonga",
    "Trinidad y Tobago",
    "Turkmenistán",
    "Tuvalu",
    "Uzbekistán",
    "Vanuatu",
    "Ciudad del Vaticano",
    "Islas Cook",
    "Niue",
    "Hong Kong",
    "Macao",
    "Islas Feroe",
    "Gibraltar",
    "Aruba",
    "Curazao",
    "Nueva Caledonia",
    "Tahití",
    "Bermudas",
    "Islas Caimán",
    "Puerto Rico",
    "Guam",
    "Samoa Americana",
    "Islas Vírgenes Estadounidenses",
    "Islas Vírgenes Británicas",
    "Montserrat",
    "Anguila",
    "Islas Turcas y Caicos",
    "Sint Maarten",
    "Islas Marianas del Norte",
  ],

};
