// Países del mundo divididos por reconocimiento de bandera a nivel mundial
// inicio  → las 5 banderas más icónicas, usadas en el modo banderas de inicio
// easy    → banderas muy icónicas y ampliamente reconocidas
// medium  → banderas conocidas regionalmente o con elementos distintivos
// hard    → banderas poco conocidas, similares entre sí o de países pequeños
// insane  → banderas extremadamente oscuras, territorios, islas micro y similares

const COUNTRIES = {

  inicio: [
    "Estados Unidos",
    "Reino Unido",
    "Canadá",
    "Japón",
    "China",
  ],

  easy: [
    "Brasil",
    "Australia",
    "Francia",
    "Alemania",
    "Italia",
    "Inglaterra",
    "España",
    "México",
    "Argentina",
    "Sudáfrica",
    "India",
    "Rusia",
    "Suiza",
    "Suecia",
    "Noruega",
    "Dinamarca",
    "Grecia",
    "Turquía",
    "Israel",
    "Arabia Saudita",
    "Corea del Sur",
    "Portugal",
    "Países Bajos",
    "Jamaica",
  ],

  medium: [
    "Austria",
    "Bélgica",
    "Bolivia",
    "Camerún",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Croacia",
    "Cuba",
    "República Checa",
    "Ecuador",
    "Egipto",
    "Finlandia",
    "Ghana",
    "Guatemala",
    "Hungría",
    "Islandia",
    "Indonesia",
    "Irán",
    "Irak",
    "Irlanda",
    "Jordania",
    "Líbano",
    "Malasia",
    "Marruecos",
    "Nepal",
    "Nigeria",
    "Corea del Norte",
    "Pakistán",
    "Perú",
    "Polonia",
    "Catar",
    "Rumanía",
    "Senegal",
    "Serbia",
    "Singapur",
    "Eslovaquia",
    "Sudán",
    "Taiwán",
    "Tailandia",
    "Túnez",
    "Ucrania",
    "Emiratos Árabes Unidos",
    "Uruguay",
    "Venezuela",
    "Kenia",
    "Inglaterra",
    "Escocia",
    "Gales",
    "Irlanda del Norte",
    "Nueva Zelanda",
  ],

  hard: [
    "Afganistán",
    "Albania",
    "Argelia",
    "Bangladés",
    "Bosnia y Herzegovina",
    "Botsuana",
    "Bulgaria",
    "Camboya",
    "El Salvador",
    "Honduras",
    "Kazajistán",
    "Libia",
    "Nicaragua",
    "Omán",
    "Panamá",
    "Paraguay",
    "Filipinas",
    "Seychelles",
    "Sri Lanka",
    "Siria",
    "Vietnam",
    "Costa de Marfil",
    "Andorra",
    "Angola",
    "Azerbaiyán",
    "República Democrática del Congo",
    "Etiopía",
    "Kuwait",
    "Mozambique",
    "Myanmar",
    "Tanzania",
    "Uganda",
    "Yemen",
    "Zambia",
    "Zimbabue",
    "Baréin",
    "Antigua y Barbuda",
    "Armenia",
    "Bahamas",
    "Barbados",
    "Bielorrusia",
    "Belice",
    "Benín",
    "Bután",
    "Brunéi",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "República Centroafricana",
    "Chipre",
    "Chad",
    "Comoras",
    "Congo",
    "Yibuti",
    "Dominica",
    "República Dominicana",
    "Guinea Ecuatorial",
    "Eritrea",
    "Estonia",
    "Esuatini",
    "Fiyi",
    "Gabón",
    "Gambia",
    "Georgia",
    "Granada",
    "Guinea",
    "Guinea-Bisáu",
    "Guyana",
    "Haití",
    "Kiribati",
    "Kosovo",
    "Kirguistán",
    "Laos",
    "Letonia",
    "Lesoto",
    "Liberia",
    "Liechtenstein",
    "Lituania",
    "Luxemburgo",
  ],

  insane: [
    "Madagascar",
    "Malaui",
    "Maldivas",
    "Malí",
    "Malta",
    "Islas Marshall",
    "Mauritania",
    "Mauricio",
    "Micronesia",
    "Moldavia",
    "Mónaco",
    "Mongolia",
    "Montenegro",
    "Namibia",
    "Nauru",
    "Níger",
    "Macedonia del Norte",
    "Palaos",
    "Palestina",
    "Papúa Nueva Guinea",
    "Ruanda",
    "San Cristóbal y Nieves",
    "Santa Lucía",
    "San Vicente y las Granadinas",
    "Samoa",
    "San Marino",
    "Santo Tomé y Príncipe",
    "Sierra Leona",
    "Eslovenia",
    "Islas Salomón",
    "Somalia",
    "Sudán del Sur",
    "Surinam",
    "Tayikistán",
    "Timor Oriental",
    "Togo",
    "Tonga",
    "Trinidad y Tobago",
    "Turkmenistán",
    "Tuvalu",
    "Uzbekistán",
    "Vanuatu",
    "Ciudad del Vaticano",
    "Islas Cook",
    "Niue",
    "Hong Kong",
    "Macao",
    "Islas Feroe",
    "Gibraltar",
    "Aruba",
    "Curazao",
    "Nueva Caledonia",
    "Tahití",
    "Bermudas",
    "Islas Caimán",
    "Puerto Rico",
    "Guam",
    "Samoa Americana",
    "Islas Vírgenes Estadounidenses",
    "Islas Vírgenes Británicas",
    "Montserrat",
    "Anguila",
    "Islas Turcas y Caicos",
    "Islas Marianas del Norte",
    "Antártida",
  ],

};

const COUNTRY_FLAGS = {
  "Canadá":         "images/flags/canada.png",
  "Reino Unido":    "images/flags/unitedkingdom.png",
  "Estados Unidos": "images/flags/unitedstates.png",
  "China":          "images/flags/china.png",
  "Japón":          "images/flags/japan.png",
  "Brasil":         "images/flags/brazil.png",
  "Australia":      "images/flags/australia.png",
  "Alemania":       "images/flags/germany.png",
  "Francia":        "images/flags/france.png",
  "México":         "images/flags/mexico.png",
  "España":         "images/flags/spain.png",
  "Argentina":      "images/flags/argentina.png",
  "Sudáfrica":      "images/flags/southafrica.png",
  "India":          "images/flags/india.png",
  "Rusia":          "images/flags/russia.png",
  "Suiza":          "images/flags/switzerland.png",
  "Suecia":         "images/flags/sweden.png",
  "Noruega":        "images/flags/norway.png",
  "Dinamarca":      "images/flags/denmark.png",
  "Grecia":         "images/flags/greece.png",
  "Turquía":        "images/flags/turkey.png",
  "Israel":         "images/flags/israel.png",
  "Arabia Saudita": "images/flags/saudiarabia.png",
  "Corea del Sur":  "images/flags/southkorea.png",
  "Portugal":       "images/flags/portugal.png",
  "Nueva Zelanda":  "images/flags/newzealand.png",
  "Jamaica":        "images/flags/jamaica.png",
  "Kenia":          "images/flags/kenya.png",
  "Afganistán":     "images/flags/afghanistan.png",
  "Albania":        "images/flags/albania.png",
  "Argelia":        "images/flags/algeria.png",
  "Angola":         "images/flags/angola.png",
  "Austria":        "images/flags/austria.png",
  "Azerbaiyán":     "images/flags/azerbaijan.png",
  "Baréin":         "images/flags/bahrain.png",
  "Bangladés":      "images/flags/bangladesh.png",
  "Bélgica":        "images/flags/belgium.png",
  "Bolivia":        "images/flags/bolivia.png",
  "Bosnia y Herzegovina": "images/flags/bosnia.png",
  "Botsuana":       "images/flags/botswana.png",
  "Andorra":        "images/flags/andorra.png",
  "Antigua y Barbuda": "images/flags/antiguabarbuda.png",
  "Armenia":        "images/flags/armenia.png",
  "Bahamas":        "images/flags/bahamas.png",
  "Barbados":       "images/flags/barbados.png",
  "Bielorrusia":    "images/flags/belarus.png",
  "Belice":         "images/flags/belize.png",
  "Benín":          "images/flags/benin.png",
  "Bután":          "images/flags/bhutan.png",
  "Antártida":      "images/flags/antarctica.png",
  "Chile":          "images/flags/chile.png",
  "Colombia":       "images/flags/colombia.png",
  "Comoras":        "images/flags/comoros.png",
  "Islas Cook":     "images/flags/cookislands.png",
  "Costa Rica":     "images/flags/costarica.png",
  "Costa de Marfil": "images/flags/cotedivoire.png",
  "Croacia":        "images/flags/croatia.png",
  "Cuba":           "images/flags/cuba.png",
  "Chipre":         "images/flags/cyprus.png",
  "República Checa": "images/flags/czechrepublic.png",
  "República Democrática del Congo": "images/flags/drcongo.png",
  "Yibuti":         "images/flags/djibouti.png",
  "Dominica":       "images/flags/dominica.png",
  "República Dominicana": "images/flags/dominicanrepublic.png",
  "Timor Oriental": "images/flags/easttimor.png",
  "Ecuador":        "images/flags/ecuador.png",
  "Egipto":         "images/flags/egypt.png",
  "El Salvador":    "images/flags/elsalvador.png",
  "Inglaterra":     "images/flags/england.png",
  "Guinea Ecuatorial": "images/flags/equatorialguinea.png",
  "Eritrea":        "images/flags/eritrea.png",
  "Estonia":        "images/flags/estonia.png",
  "Esuatini":       "images/flags/eswatini.png",
  "Etiopía":        "images/flags/ethiopia.png",
  "Micronesia":     "images/flags/micronesia.png",
  "Fiyi":           "images/flags/fiji.png",
  "Finlandia":      "images/flags/finland.png",
  "Gabón":          "images/flags/gabon.png",
  "Gambia":         "images/flags/gambia.png",
  "Georgia":        "images/flags/georgia.png",
  "Ghana":          "images/flags/ghana.png",
  "Granada":        "images/flags/grenada.png",
  "Guatemala":      "images/flags/guatemala.png",
  "Guinea":         "images/flags/guinea.png",
  "Guinea-Bisáu":   "images/flags/guineabissau.png",
  "Guyana":         "images/flags/guyana.png",
  "Haití":          "images/flags/haiti.png",
  "Honduras":       "images/flags/honduras.png",
  "Hong Kong":      "images/flags/hongkong.png",
  "Hungría":        "images/flags/hungary.png",
  "Islandia":       "images/flags/iceland.png",
  "Indonesia":      "images/flags/indonesia.png",
  "Irán":           "images/flags/iran.png",
  "Irak":           "images/flags/iraq.png",
  "Irlanda":        "images/flags/ireland.png",
  "Italia":         "images/flags/italy.png",
  "Jordania":       "images/flags/jordan.png",
  "Kazajistán":     "images/flags/kazakhstan.png",
  "Kiribati":       "images/flags/kiribati.png",
  "Kosovo":         "images/flags/kosovo.png",
  "Kuwait":         "images/flags/kuwait.png",
  "Kirguistán":     "images/flags/kyrgyzstan.png",
  "Laos":           "images/flags/laos.png",
  "Letonia":        "images/flags/latvia.png",
  "Líbano":         "images/flags/lebanon.png",
  "Lesoto":         "images/flags/lesotho.png",
  "Liberia":        "images/flags/liberia.png",
  "Libia":          "images/flags/libya.png",
  "Liechtenstein":  "images/flags/liechtenstein.png",
  "Lituania":       "images/flags/lithuania.png",
  "Luxemburgo":     "images/flags/luxembourg.png",
  "Madagascar":     "images/flags/madagascar.png",
  "Malaui":         "images/flags/malawi.png",
  "Malasia":        "images/flags/malaysia.png",
  "Maldivas":       "images/flags/maldives.png",
  "Malí":           "images/flags/mali.png",
  "Malta":          "images/flags/malta.png",
  "Islas Marshall": "images/flags/marshallislands.png",
  "Mauritania":     "images/flags/mauritania.png",
  "Mauricio":       "images/flags/mauritius.png",
  "Moldavia":       "images/flags/moldova.png",
  "Mónaco":         "images/flags/monaco.png",
  "Mongolia":       "images/flags/mongolia.png",
  "Montenegro":     "images/flags/montenegro.png",
  "Marruecos":      "images/flags/morocco.png",
  "Mozambique":     "images/flags/mozambique.png",
  "Myanmar":        "images/flags/myanmar.png",
  "Namibia":        "images/flags/namibia.png",
  "Nauru":          "images/flags/nauru.png",
  "Nepal":          "images/flags/nepal.png",
  "Países Bajos":   "images/flags/netherlands.png",
  "Nicaragua":      "images/flags/nicaragua.png",
  "Níger":          "images/flags/niger.png",
  "Nigeria":        "images/flags/nigeria.png",
  "Niue":           "images/flags/niue.png",
  "Corea del Norte": "images/flags/northkorea.png",
  "Macedonia del Norte": "images/flags/northmacedonia.png",
  "Omán":           "images/flags/oman.png",
  "Pakistán":       "images/flags/pakistan.png",
  "Palaos":         "images/flags/palau.png",
  "Palestina":      "images/flags/palestine.png",
  "Panamá":         "images/flags/panama.png",
  "Papúa Nueva Guinea": "images/flags/papuanewguinea.png",
  "Paraguay":       "images/flags/paraguay.png",
  "Perú":           "images/flags/peru.png",
  "Filipinas":      "images/flags/philippines.png",
  "Polonia":        "images/flags/poland.png",
  "Catar":          "images/flags/qatar.png",
  "Congo":          "images/flags/congo.png",
  "Rumanía":        "images/flags/romania.png",
  "Ruanda":         "images/flags/rwanda.png",
  "San Cristóbal y Nieves": "images/flags/saintkitts.png",
  "Santa Lucía":    "images/flags/saintlucia.png",
  "San Vicente y las Granadinas": "images/flags/saintvincent.png",
  "Samoa":          "images/flags/samoa.png",
  "San Marino":     "images/flags/sanmarino.png",
  "Santo Tomé y Príncipe": "images/flags/saotome.png",
  "Escocia":        "images/flags/scotland.png",
  "Senegal":        "images/flags/senegal.png",
  "Serbia":         "images/flags/serbia.png",
  "Seychelles":     "images/flags/seychelles.png",
  "Sierra Leona":   "images/flags/sierraleone.png",
  "Singapur":       "images/flags/singapore.png",
  "Eslovaquia":     "images/flags/slovakia.png",
  "Eslovenia":      "images/flags/slovenia.png",
  "Islas Salomón":  "images/flags/solomonislands.png",
  "Somalia":        "images/flags/somalia.png",
  "Sudán del Sur":  "images/flags/southsudan.png",
  "Sri Lanka":      "images/flags/srilanka.png",
  "Sudán":          "images/flags/sudan.png",
  "Surinam":        "images/flags/suriname.png",
  "Siria":          "images/flags/syria.png",
  "Taiwán":         "images/flags/taiwan.png",
  "Tayikistán":     "images/flags/tajikistan.png",
  "Tanzania":       "images/flags/tanzania.png",
  "Tailandia":      "images/flags/thailand.png",
  "Togo":           "images/flags/togo.png",
  "Tonga":          "images/flags/tonga.png",
  "Trinidad y Tobago": "images/flags/trinidadtobago.png",
  "Túnez":          "images/flags/tunisia.png",
  "Turkmenistán":   "images/flags/turkmenistan.png",
  "Tuvalu":         "images/flags/tuvalu.png",
  "Uganda":         "images/flags/uganda.png",
  "Ucrania":        "images/flags/ukraine.png",
  "Emiratos Árabes Unidos": "images/flags/uae.png",
  "Uruguay":        "images/flags/uruguay.png",
  "Uzbekistán":     "images/flags/uzbekistan.png",
  "Vanuatu":        "images/flags/vanuatu.png",
  "Ciudad del Vaticano": "images/flags/vatican.png",
  "Venezuela":      "images/flags/venezuela.png",
  "Vietnam":        "images/flags/vietnam.png",
  "Gales":          "images/flags/wales.png",
  "Yemen":          "images/flags/yemen.png",
  "Zambia":         "images/flags/zambia.png",
  "Zimbabue":       "images/flags/zimbabwe.png",
  "Irlanda del Norte": "images/flags/northireland.png",
  "Macao":          "images/flags/macau.png",
  "Islas Feroe":    "images/flags/faroeislands.png",
  "Gibraltar":      "images/flags/gibraltar.png",
  "Aruba":          "images/flags/aruba.png",
  "Curazao":        "images/flags/curacao.png",
  "Nueva Caledonia": "images/flags/newcaledonia.png",
  "Tahití":         "images/flags/tahiti.png",
  "Bermudas":       "images/flags/bermuda.png",
  "Islas Caimán":   "images/flags/caymanislands.png",
  "Puerto Rico":    "images/flags/puertorico.png",
  "Guam":           "images/flags/guam.png",
  "Samoa Americana": "images/flags/americansamoa.png",
  "Islas Vírgenes Estadounidenses": "images/flags/usvirginislands.png",
  "Islas Vírgenes Británicas": "images/flags/britishvirginislands.png",
  "Montserrat":     "images/flags/monserrat.png",
  "Anguila":        "images/flags/anguila.png",
  "Islas Turcas y Caicos": "images/flags/turksandcaicos.png",
  "Islas Marianas del Norte": "images/flags/northernmarianaislands.png",
  "Brunéi":         "images/flags/brunei.png",
  "Bulgaria":       "images/flags/bulgaria.png",
  "Burkina Faso":   "images/flags/burkinafaso.png",
  "Burundi":        "images/flags/burundi.png",
  "Camboya":        "images/flags/cambodia.png",
  "Camerún":        "images/flags/cameroon.png",
  "Cabo Verde":     "images/flags/capeverde.png",
  "República Centroafricana": "images/flags/centralafricanrepublic.png",
  "Chad":           "images/flags/chad.png",
};
